### ISSUE TITLE
"post" transform

### ISSUE THREAD

**Issue by goto-bus-stop** [stackhtml/documentify#15]
Bankai adds some transforms that run after your package.json transforms, but sometimes you want to do things to your html at the end. Maybe edit some bankai-inserted nodes (eg https://github.com/choojs/bankai/issues/315) or [minifying the server-rendered document](https://github.com/goto-bus-stop/html-minify-stream).

We could implement this quite easily using a [labeled-stream-splicer](https://npmjs.com/package/labeled-stream-splicer), with labels for package.json transforms, transforms added through the API, and transforms that should run at the end.

Two ideas for how configuration could work for that:

* A separate `postTransform` key

```json
{
  "documentify": {
    "transform": [ "./run-first" ],
    "postTransform": [ "./run-last" ]
  }
}
```
```js
Documentify()
  .transform('./run-first')
  .postTransform('./run-last')
```

* An `order` option on transforms to specify the label. eg, with labels `pre`, `mid`, `post`:

```js
{
  "documentify": {
    "transform": [
      "./run-first", // default order: "pre"
      ["./run-last", { "order": "post" }],
    ]
  }
}
```
```js
Documentify()
  .transform('./run-first') // default order: "mid"
  .transform('./run-last', { order: 'post' })
```

**Comment by Flet** [comment]
Cool! I'm happy to be a lab rat for this as I have relevant use case (modifying index.html after bankai is done with it).

I like the `order` option as it doesn't change the interface :)

 - Would it make sense to use a value to determine the order? (sort of how `z-index` works?)
 - What about using `{order: 'first'}` and `{order: 'last'}`? 
   - `pre` and `post` may be confusing outside of the context of `bankai`?

**Comment by goto-bus-stop** [comment]
> Would it make sense to use a value to determine the order? 

I think that'd be confusing because they are already sorted in some way in the transforms array. I'm not sure how that would work with bankai adding `.transform()`s too--maybe those would be at index 0, but then you'd have to manually add -1, -2 to all your own transforms

> What about using `{order: 'first'}` and `{order: 'last'}`? 
> `pre` and `post` may be confusing outside of the context of `bankai`?

yeah! `pre` and `post` are definitely a bit weird if you're not using a tool that adds its own transforms. i'd maybe go for `start` and `end` instead of `first` and `last` because to me it sounds odd to add two transforms that run 'last'.

I'll prototype something with the `order` option in a bit!

**Comment by Flet** [comment]
Nice! 👍   `start`/`end` sound good!

**Comment by yoshuawuyts** [comment]
I dig this idea!

**Comment by goto-bus-stop** [comment]
:package: 3.2.0
