### ISSUE TITLE
Accept input stream

### ISSUE THREAD

**Issue by rreusser** [stackhtml/documentify#16]
Currently I need to type:

```sh
$ browserify index.js | indexhtmlify > index.html
$ documentify index.html > index2.html
```

I'd love to able to type:

```sh
$ browserify index.js | indexhtmlify | documentify > index.html
```

I've been digging a bit and don't necessarily see barriers to this apart from the fact that it just doesn't pass configuration through in a way that makes this perfectly natural. I'm curious: is this desirable? Are there reasons this is intentionally not done?

I love the project in general and am glad to make a PR for this if it's desired.

Thanks!

**Comment by yoshuawuyts** [comment]
This sounds pretty cool; not seeing any particular reasons why this wouldn't be desirable (:
